export enum MarkType {
  ALFA_ROMEO = 'Alfa Romeo',
  AUDI = 'Audi',
  BMW = 'BMW',
  CITROËN = 'Citroën',
  DACIA = 'Dacia',
  DAEWOO = 'Daewoo',
  FIAT = 'Fiat',
  FORD = 'Ford',
  HONDA = 'Honda',
  HYUNDAI = 'Hyundai',
  KIA = 'Kia',
  LEXUS = 'Lexus',
  MERCEDES = 'Mercedes',
  NISSAN = 'Nissan',
  OPEL = 'Opel',
  PEUGEOT = 'Peugeot',
  RENAULT = 'Renault',
  SEAT = 'Seat',
  SKODA = 'Skoda',
  TOYOTA = 'Toyota',
  VOLKSWAGEN = 'Volkswagen',
  VOLVO = 'Volvo',
  MINI = 'Mini',
  MITSUBISHI = 'Mitsubishi',
  FERRARI = 'Ferrari',
  MAZDA = 'Mazda',
}
